typography_spectrum: 0.57333
color:
  brandColors:
    - '#af1f24'
    - '#eeef95'
    - '#ba4639'
    - '#c56b4a'
    - '#d6a664'
  brandStrength: 0
  lightness: 0.5625
  saturation: 0.875
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.30967
analytics:
  google: null
  facebook: null
  twitter: null
name: StandbyRolling
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: RECORD | MIX | CONSULT
purpose: []
