name: StandbyRolling
favicon: null
layout_spectrum: 0.7399722896516323
typography_spectrum: 0.5562541757244617
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.28102129558101296
  lightness: 0.9637943401467055
  saturation: 0.2271180881652981
  rhythmicContrast: 0.09120708680711687
purpose: []
